// app/layout.tsx
import type { Metadata } from "next"
import { Montserrat, Raleway } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers" // 👈 Import the wrapper

const montserrat = Montserrat({
  weight: "800",
  subsets: ["latin"],
  variable: "--font-heading",
})

const raleway = Raleway({
  weight: "600",
  subsets: ["latin"],
  variable: "--font-body",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable} ${raleway.variable} antialiased`}>
        <Providers>{children}</Providers> {/* ✅ Redux provider works here safely */}
      </body>
    </html>
  )
}
